version: "3.9"

services:
  movie-db:
    image: postgres:16
    container_name: movie-db
    environment:
      - POSTGRES_DB=cinema_moviedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ../movie-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservice-net

  movie-service:
    build: ../movie-service
    container_name: movie-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://movie-db:5432/cinema_moviedb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      movie-db:
        condition: service_healthy
    networks:
      - microservice-net

networks:
  microservice-net:
    external: true
