version: "3.9"

services:
  session-db:
    image: postgres:16
    container_name: session-db
    environment:
      POSTGRES_DB: cinema_sessiondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../session-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservice-net

  session-service:
    build: ../session-service
    container_name: session-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://session-db:5432/cinema_sessiondb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      session-db:
        condition: service_healthy
    networks:
      - microservice-net

networks:
  microservice-net:
    external: true
