version: "3.9"

services:
  ticket-db:
    image: postgres:16
    container_name: ticket-db
    environment:
      POSTGRES_DB: cinema_ticketdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservice-net

  ticket-service:
    build: ../ticket-service
    container_name: ticket-service
    ports:
      - "8082:8082"
    depends_on:
      ticket-db:
        condition: service_healthy

    networks:
      - microservice-net
networks:
  microservice-net:
    external: true
